# Generated by Django 2.2.6 on 2019-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0002_auto_20191027_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarpluginmodel',
            name='items',
        ),
        migrations.AddField(
            model_name='navbarpluginmodel',
            name='items',
            field=models.ManyToManyField(to='djangocms_bulma.Link'),
        ),
    ]
