# Generated by Django 2.2.6 on 2019-10-27 17:58

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0006_cardpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpluginmodel',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
