# Generated by Django 2.2.6 on 2019-10-27 23:04

from django.db import migrations, models
import django.db.models.deletion
import djangocms_bulma.utils
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_bulma', '0007_cardpluginmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_bulma_heropluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('full_height', models.BooleanField(blank=True, default=True)),
                ('with_navbar', models.BooleanField(blank=True, default=False)),
                ('title', djangocms_text_ckeditor.fields.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_bulma.utils.LabelFieldMixin, 'cms.cmsplugin'),
        ),
    ]
