# Generated by Django 2.2.6 on 2019-10-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0008_heropluginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heropluginmodel',
            old_name='title',
            new_name='content',
        ),
    ]
