# Generated by Django 2.2.6 on 2019-10-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0009_auto_20191027_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpluginmodel',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='heropluginmodel',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
