# Generated by Django 2.2.6 on 2019-10-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0010_auto_20191027_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpluginmodel',
            old_name='content',
            new_name='html_content',
        ),
        migrations.RenameField(
            model_name='heropluginmodel',
            old_name='content',
            new_name='html_content',
        ),
    ]
