# Generated by Django 2.2.6 on 2019-10-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0011_auto_20191027_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpluginmodel',
            old_name='html_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='heropluginmodel',
            old_name='html_content',
            new_name='content',
        ),
    ]
