# Generated by Django 2.2.6 on 2019-11-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_bulma', '0014_contactformpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_bulma_socialmediapluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('icon_class', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
