# Generated by Django 2.2.6 on 2019-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_bulma', '0015_socialmediapluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapluginmodel',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
