# Generated by Django 2.2.6 on 2019-11-04 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_bulma', '0016_socialmediapluginmodel_open_in_new_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_bulma_imagepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('image_class', models.CharField(blank=True, max_length=200, verbose_name='Class')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
