# Generated by Django 2.2.6 on 2019-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('other_fields', models.CharField(blank=True, max_length=1000)),
                ('sent', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
